# Generated by Django 4.2.1 on 2023-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgFileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('avatar', models.FileField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='文件名')),
            ],
        ),
    ]
